### ISSUE TITLE
Override instead of append for class names

### ISSUE THREAD

**Issue by stanislav-ermakov-roi** [glennflanagan/react-collapsible#89] opened 2018-04-11 08:37 UTC
In our project we use css modules and would actually like to override classes instead of appending them to static classes of component. Could this be considered for v3? To make it backwards compatible an additional prop overrideClassNames could be added for example.

**Comment by karltaylor** [comment] 2018-04-11 13:15
I think this is a duplicate of #76. There's a solution that I used for CSS Modules in there as well. Will look into it for v3.

**Closed by karltaylor** 2018-04-11 13:15 UTC

**Comment by stanislav-ermakov-roi** [comment] 2018-04-11 14:10
I've seen #76, but the subject is overridable state classes there if I'm not mistaken. I want to get rid of static classes at all when classes are passed as props, because static classes are not used in that case.

**Comment by karltaylor** [comment] 2021-09-29 15:42
Closing due to inactivity
