### ISSUE TITLE
Warning: Prop `id` did not match.

### ISSUE THREAD

**Issue by neatbyte-vkovalchuk** [glennflanagan/react-collapsible#214] opened 2021-11-04 12:12 UTC
Warning: Prop `id` did not match. Server: "collapsible-trigger-1636024544094" Client: "collapsible-trigger-1636024546217"

![image](https://user-images.githubusercontent.com/91458653/140311422-348eb00c-8056-433e-9682-f39c91110b52.png)

**Comment by glennflanagan** [comment] 2021-11-04 12:13
Closing as is a duplicate of #210

**Closed by glennflanagan** 2021-11-04 12:13 UTC
Labels: duplicate
