### ISSUE TITLE
Open on mount doesn't work

### ISSUE THREAD

**Issue by falconmick** [glennflanagan/react-collapsible#97] opened 2018-05-25 03:26 UTC
I have a Collapsable that uses open={true} to have it open by default. When I look into the markup I see:

`Collapsible__trigger is-open`

but I also see:

```
<div 
    class="Collapsible__contentOuter"
    style="height:0;-webkit-transition:height 400ms linear;-ms-transition:height 400ms linear;transition:height 400ms linear;overflow:hidden;"
>stuffhere</div>
```

so basically it's open with a height of zero.. I think that when it starts in an open state it's not running the animation/starting out with the correct height of an open collapsible

**Comment by falconmick** [comment] 2018-05-25 06:44
Hey I’m gonna be one of those people and say that I’m probably not going to
have time to.

I needed to add a collapsible area to my existing app so I looked to use
this and either by my own mis usage or a bug it didn’t work as expected.

I just thought I would put this here encase it rang bells to any devs who
would know of the issue, I ended up having to roll my own and in the
process I looked at your code and it looks like you do check for open true
on the constructor so either I messed up really weird or that part of the
code is broken.

If I get time I’ll make a fiddle but I really doubt it. Sorry

**Comment by glennflanagan** [comment] 2018-05-25 07:49
No problem. If this was an issue with the code I think we'd have a ton more issues raised. I'll close the issue for now, feel free to reopen if you get time to replicate.

**Closed by glennflanagan** 2018-05-25 07:49 UTC

**Comment by karltaylor** [comment] 2018-05-25 10:04
Remember you don't need to add `true` to a prop if it's a boolean

https://jsfiddle.net/sctqwpnh/

**Comment by falconmick** [comment] 2018-05-25 11:27
Try/false was being sent down from something else. Probably the spot of the
issue if it were in my code

**Comment by acha5066** [comment] 2019-10-24 07:18
I know this issue has been closed but I just wanted to point out that I have a similar, if not the same problem. Setting `open={true}` works just fine, as does normal toggling. I think the problem is that the Collapsible component is not re-rendering when the parent components props change. 

To give you an example using redux. I have two components `SmartContainer` and `DumpComponent`. DumbComponent gets passed an `open` prop from `SmartContainer` and passes it on to the `Collapsible` component.

The open prop is calculated in `SmartContainer` and is based on some state that might not exist yet so even though the values indicate `open` should be set true, there's every change it will be `false` first.

My console.log output looks like this:

```
false
true
```

I have the same outcome as @falconmick. The `is-open` class is applied but `height` is `0` .

**Comment by pmourer** [comment] 2019-12-03 20:05
@acha5066 @falconmick this is definitely still an issue.

I believe I have traced the cause to the following scenario:
- parent component mounts with state for collapsible open to false
- parent component state changes for collapsible open to true
- parent component re-renders
- collapsible now has state open=true, height=0

**Comment by pmourer** [comment] 2019-12-03 20:15
The above scenario seems to not happen in a class react component using setState, but in a functional component that does not store open in state, the above is present

**Comment by pmourer** [comment] 2019-12-03 20:45
Here is the fiddle i made that seemed to represent my situation, however in this fiddle everything works as expected so i'm a little perplexed

https://jsfiddle.net/wcfn4d9x/1/

**Comment by pmourer** [comment] 2019-12-03 21:36
For some reason in my case,
https://github.com/glennflanagan/react-collapsible/blob/develop/src/Collapsible.js#L92
innerRef.scrollHeight is 0 at the time the setState is run

**Comment by pmourer** [comment] 2019-12-03 22:10
OK -- i think i determined the issue in my case, the component that contains the collapsible was not displayed during all of this so measure height of the containing elements was 0?

**Comment by pmourer** [comment] 2019-12-03 22:19
Confirmed -- this was because a parent element had "display: none" at the time that the open property was being set to true. changing the parent element to use "visibility: hidden" resolved the issue for me
